### ISSUE TITLE
fork/exec /usr/bin/curl: no such file or directory

### ISSUE THREAD

**Issue by rreddykeap** [google/oauth2l#115]
I am running a CronJob with curl by passing --url and --scpope.

I am getting the below error:

`fork/exec /usr/bin/curl: no such file or directory`

**Comment by rreddykeap** [comment]
```
apiVersion: batch/v1beta1
kind: CronJob
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: abcd
              image: gcr.io/oauth2l/oauth2l
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/secrets/creds.json"
              args:
                - curl
                - --url
                - http://google.com
                - --scope
                - cloud-platform
                - --
                - -i

```
